# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/system.xdc

# Block Designs: bd/zynq_design_1/zynq_design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1 || ORIG_REF_NAME==zynq_design_1}]

# IP: bd/zynq_design_1/ip/zynq_design_1_processing_system7_1_0/zynq_design_1_processing_system7_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_processing_system7_1_0 || ORIG_REF_NAME==zynq_design_1_processing_system7_1_0}]

# IP: bd/zynq_design_1/ip/zynq_design_1_axi_gpio_1_0/zynq_design_1_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_axi_gpio_1_0 || ORIG_REF_NAME==zynq_design_1_axi_gpio_1_0}]

# IP: bd/zynq_design_1/ip/zynq_design_1_axi_gpio_2_1/zynq_design_1_axi_gpio_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_axi_gpio_2_1 || ORIG_REF_NAME==zynq_design_1_axi_gpio_2_1}]

# IP: bd/zynq_design_1/ip/zynq_design_1_axi_gpio_3_2/zynq_design_1_axi_gpio_3_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_axi_gpio_3_2 || ORIG_REF_NAME==zynq_design_1_axi_gpio_3_2}]

# IP: bd/zynq_design_1/ip/zynq_design_1_processing_system7_1_axi_periph_0/zynq_design_1_processing_system7_1_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_processing_system7_1_axi_periph_0 || ORIG_REF_NAME==zynq_design_1_processing_system7_1_axi_periph_0}]

# IP: bd/zynq_design_1/ip/zynq_design_1_proc_sys_reset_0/zynq_design_1_proc_sys_reset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_proc_sys_reset_0 || ORIG_REF_NAME==zynq_design_1_proc_sys_reset_0}]

# IP: bd/zynq_design_1/ip/zynq_design_1_axi_emc_1_0/zynq_design_1_axi_emc_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_axi_emc_1_0 || ORIG_REF_NAME==zynq_design_1_axi_emc_1_0}]

# IP: bd/zynq_design_1/ip/zynq_design_1_xlconstant_0_0/zynq_design_1_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_xlconstant_0_0 || ORIG_REF_NAME==zynq_design_1_xlconstant_0_0}]

# IP: bd/zynq_design_1/ip/zynq_design_1_xbar_0/zynq_design_1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_xbar_0 || ORIG_REF_NAME==zynq_design_1_xbar_0}]

# IP: bd/zynq_design_1/ip/zynq_design_1_auto_pc_0/zynq_design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_auto_pc_0 || ORIG_REF_NAME==zynq_design_1_auto_pc_0}]

# IP: bd/zynq_design_1/ip/zynq_design_1_auto_pc_1/zynq_design_1_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_auto_pc_1 || ORIG_REF_NAME==zynq_design_1_auto_pc_1}]

# IP: bd/zynq_design_1/ip/zynq_design_1_auto_pc_2/zynq_design_1_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_auto_pc_2 || ORIG_REF_NAME==zynq_design_1_auto_pc_2}]

# IP: bd/zynq_design_1/ip/zynq_design_1_auto_pc_3/zynq_design_1_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_auto_pc_3 || ORIG_REF_NAME==zynq_design_1_auto_pc_3}]

# XDC: bd/zynq_design_1/ip/zynq_design_1_processing_system7_1_0/zynq_design_1_processing_system7_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_design_1_processing_system7_1_0 || ORIG_REF_NAME==zynq_design_1_processing_system7_1_0}] {/inst }]/inst ]]

# XDC: bd/zynq_design_1/ip/zynq_design_1_axi_gpio_1_0/zynq_design_1_axi_gpio_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_design_1_axi_gpio_1_0 || ORIG_REF_NAME==zynq_design_1_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: bd/zynq_design_1/ip/zynq_design_1_axi_gpio_1_0/zynq_design_1_axi_gpio_1_0_ooc.xdc

# XDC: bd/zynq_design_1/ip/zynq_design_1_axi_gpio_1_0/zynq_design_1_axi_gpio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_design_1_axi_gpio_1_0 || ORIG_REF_NAME==zynq_design_1_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: bd/zynq_design_1/ip/zynq_design_1_axi_gpio_2_1/zynq_design_1_axi_gpio_2_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_design_1_axi_gpio_2_1 || ORIG_REF_NAME==zynq_design_1_axi_gpio_2_1}] {/U0 }]/U0 ]]

# XDC: bd/zynq_design_1/ip/zynq_design_1_axi_gpio_2_1/zynq_design_1_axi_gpio_2_1_ooc.xdc

# XDC: bd/zynq_design_1/ip/zynq_design_1_axi_gpio_2_1/zynq_design_1_axi_gpio_2_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_design_1_axi_gpio_2_1 || ORIG_REF_NAME==zynq_design_1_axi_gpio_2_1}] {/U0 }]/U0 ]]

# XDC: bd/zynq_design_1/ip/zynq_design_1_axi_gpio_3_2/zynq_design_1_axi_gpio_3_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_design_1_axi_gpio_3_2 || ORIG_REF_NAME==zynq_design_1_axi_gpio_3_2}] {/U0 }]/U0 ]]

# XDC: bd/zynq_design_1/ip/zynq_design_1_axi_gpio_3_2/zynq_design_1_axi_gpio_3_2_ooc.xdc

# XDC: bd/zynq_design_1/ip/zynq_design_1_axi_gpio_3_2/zynq_design_1_axi_gpio_3_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_design_1_axi_gpio_3_2 || ORIG_REF_NAME==zynq_design_1_axi_gpio_3_2}] {/U0 }]/U0 ]]

# XDC: bd/zynq_design_1/ip/zynq_design_1_proc_sys_reset_0/zynq_design_1_proc_sys_reset_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_proc_sys_reset_0 || ORIG_REF_NAME==zynq_design_1_proc_sys_reset_0}]

# XDC: bd/zynq_design_1/ip/zynq_design_1_proc_sys_reset_0/zynq_design_1_proc_sys_reset_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_proc_sys_reset_0 || ORIG_REF_NAME==zynq_design_1_proc_sys_reset_0}]

# XDC: bd/zynq_design_1/ip/zynq_design_1_proc_sys_reset_0/zynq_design_1_proc_sys_reset_0_ooc.xdc

# XDC: bd/zynq_design_1/ip/zynq_design_1_axi_emc_1_0/zynq_design_1_axi_emc_1_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_axi_emc_1_0 || ORIG_REF_NAME==zynq_design_1_axi_emc_1_0}]

# XDC: bd/zynq_design_1/ip/zynq_design_1_axi_emc_1_0/zynq_design_1_axi_emc_1_0_ooc.xdc

# XDC: bd/zynq_design_1/ip/zynq_design_1_xbar_0/zynq_design_1_xbar_0_ooc.xdc

# XDC: bd/zynq_design_1/ip/zynq_design_1_auto_pc_0/zynq_design_1_auto_pc_0_ooc.xdc

# XDC: bd/zynq_design_1/ip/zynq_design_1_auto_pc_1/zynq_design_1_auto_pc_1_ooc.xdc

# XDC: bd/zynq_design_1/ip/zynq_design_1_auto_pc_2/zynq_design_1_auto_pc_2_ooc.xdc

# XDC: bd/zynq_design_1/ip/zynq_design_1_auto_pc_3/zynq_design_1_auto_pc_3_ooc.xdc

# XDC: bd/zynq_design_1/zynq_design_1_ooc.xdc
